testNG_HW
SvyatoslavQA/AQA_Prilutskiy pull request #1
Opened 2024-03-10 11:39 UTC by SvyatoslavQA

testNG_HW готово к ревью

2024-03-10 21:11 UTC, wildpioneer requested changes

2024-03-10 21:11 UTC, wildpioneer commented on src/test/java/BaseTest.java
> +    @BeforeSuite
Файлы не относящиеся к ДЗ необходимо удалять из бранча и не отправлять в PR

2024-03-10 21:11 UTC, wildpioneer commented on src/test/java/CalcTest.java
> +    @Test(testName = "retryAttempt", retryAnalyzer = Retry.class)
Форматирование - между методами должна быть пустая строка

2024-03-10 21:11 UTC, wildpioneer commented on src/test/java/CalcTest.java
> +    @Test(testName = "exception check")
Отсутствует тест на @Parameters

2024-03-17 22:08 UTC, SvyatoslavQA commented
оценка устраивает

2024-03-25 14:29 UTC, wildpioneer commented
Проверено

2024-03-25 14:29 UTC, closed without merging