Selenium basic hw
SvyatoslavQA/AQA_Prilutskiy pull request #2
Opened 2024-03-10 17:57 UTC by SvyatoslavQA

SeleniumBasic HW ready for review

2024-03-10 21:14 UTC, wildpioneer requested changes

2024-03-10 21:14 UTC, wildpioneer commented on src/test/java/SkfTest.java
> +        Assert.assertTrue(mdrdResult.getText().startsWith("75.11 мл/мин"));
Форматирование - пустыми строками мы отделяем логические блоки
Передо на новую страницу
Проверки

2024-03-10 21:14 UTC, wildpioneer commented on src/test/java/LaminatTest.java
> +
Не оставляй пустые строки перед закрытием метода

2024-03-17 22:08 UTC, SvyatoslavQA commented
оценка устраивает

2024-03-25 14:29 UTC, wildpioneer commented
Проверено

2024-03-25 14:29 UTC, closed without merging