Locators not finished
SvyatoslavQA/AQA_Prilutskiy pull request #3
Opened 2024-03-10 20:29 UTC by SvyatoslavQA

Locators not finished

2024-03-10 21:15 UTC, wildpioneer commented
Подожду пока закончишь

2024-03-17 22:13 UTC, SvyatoslavQA commented
Please review

2024-03-18 11:02 UTC, wildpioneer requested changes

2024-03-18 11:02 UTC, wildpioneer commented on src/test/java/LocatorTest.java
> +    }
Отсутствуют следующие локаторы:
classname
tagname
linktext
partial linktext
**XPath**
ancestor
following
parent
preceding
**CSS**
.class1.class2
.class1 .class2
tagname
tagname.class
[attribute~=value]
[attribute|=value]
[attribute^=value]
[attribute$=value]
[attribute*=value]

2024-03-24 14:53 UTC, SvyatoslavQA commented on src/test/java/LocatorTest.java
> +    }
please review last commit, thanks

2024-03-25 14:28 UTC, wildpioneer commented
Проверено

2024-03-25 14:28 UTC, closed without merging